# Generated by Django 3.2.7 on 2021-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=30),
        ),
    ]
